//
// Created by saphieron on 4/27/21.
//

#ifndef SAPH_PICO_TEMPERATURE_TEST_SAPHBME280_TEST_DEFINITIONS_H
#define SAPH_PICO_TEMPERATURE_TEST_SAPHBME280_TEST_DEFINITIONS_H

#define NO_ERROR 0
#define WRITE_ERROR -11
#define READ_ERROR -12
#define ERROR_PLATFORM_GENERIC -2
#define NULL_POINTER_ERROR -20
#define ADDRESS_RESERVED_ERROR -30

#define LOWEST_THREE_BITS 7

#define MEASUREMENT_SIZE 8

#define TEST_OVERSAMPLING_SKIP 0x00
#define TEST_OVERSAMPLING_x1 0x01
#define TEST_OVERSAMPLING_x2 0x02
#define TEST_OVERSAMPLING_x4 0x03
#define TEST_OVERSAMPLING_x8 0x04
#define TEST_OVERSAMPLING_x16 0x05

#define SENSOR_MODE_SLEEP 0
#define SENSOR_MODE_FORCED 2
#define SENSOR_MODE_NORMAL 3

#define STANDBY_TIME_MS_0_5 0x00
#define STANDBY_TIME_MS_62_5 0x01
#define STANDBY_TIME_MS_125_0 0x02
#define STANDBY_TIME_MS_250_0 0x03
#define STANDBY_TIME_MS_500_0 0x04
#define STANDBY_TIME_MS_1000_0 0x05
#define STANDBY_TIME_MS_10_0 0x06
#define STANDBY_TIME_MS_20_0 0x07

#define IIR_FILTER_COEFFICIENT_OFF 0x00
#define IIR_FILTER_COEFFICIENT_2 0x01
#define IIR_FILTER_COEFFICIENT_4 0x02
#define IIR_FILTER_COEFFICIENT_8 0x03
#define IIR_FILTER_COEFFICIENT_16 0x04

#define firstBurstReadAmount 25
#define secondBurstReadAmount 1
#define thirdBurstReadAmount 7
#define BURST_ADDR_FIRST 0x88

#define LOWER_FOUR_BITS 0x0F

#endif //SAPH_PICO_TEMPERATURE_TEST_SAPHBME280_TEST_DEFINITIONS_H
