//
// Created by saphieron on 4/28/21.
//

#ifndef SAPH_PICO_TEMPERATURE_TEST_SAPH_SSD1306_TEST_DEFINITIONS_H
#define SAPH_PICO_TEMPERATURE_TEST_SAPH_SSD1306_TEST_DEFINITIONS_H

#define NO_ERROR 0
#define WRITE_ERROR -11
#define READ_ERROR -12
#define ERROR_PLATFORM_GENERIC -2
#define NULL_POINTER_ERROR -20
//#define ADDRESS_RESERVED_ERROR -30

#endif //SAPH_PICO_TEMPERATURE_TEST_SAPH_SSD1306_TEST_DEFINITIONS_H
